=== BackupTheBerlios/ruff-svn/trunk/ruff.dtd
<!--                    papo report dtd                            -->
<!--
Copyright 2003 Fundacion Via Libre

This file is part of PAPO.

PAPO is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

PAPO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PAPO; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-->


<!ENTITY % headers "header|page_header|partial_header">
<!ENTITY % footers "footer|page_footer|partial_footer">
<!ENTITY % style   "style CDATA '12cpi'">


<!ELEMENT  report            (%headers;|%footers;|detail|detail_entry)+ 
                                                                     >
<!ATTLIST  report
             name       NMTOKEN                            #REQUIRED
             max_height CDATA                              #IMPLIED
             max_num_pages
                        CDATA                              "1"
             output_encoding
                        CDATA                              "cp850"
             printer    CDATA                              "escp"
             %style;
             height     CDATA                              #IMPLIED  >

<!ELEMENT  detail            (%headers;|%footers;|detail|detail_entry)+ 
                                                                     >
<!ATTLIST  detail
             name       NMTOKEN                            #REQUIRED
             %style;
             height     CDATA                              #IMPLIED  >


<!--                    what goes at the start of the detail       -->
<!ELEMENT  header            (box)+                                  >
<!ATTLIST  header
             %style;
             height     CDATA                              #IMPLIED  >
<!--                    what goes at the end of the detail         -->
<!ELEMENT  footer           (box)+                                  >
<!ATTLIST  footer
             %style;
             height     CDATA                              #IMPLIED  >
<!--                    what goes at the top of each page          -->
<!ELEMENT  page_header       (box)+                                  >
<!ATTLIST  page_header
             %style;
             height     CDATA                              #IMPLIED  >
<!--                    what goes at the bottom of each page       -->
<!ELEMENT  page_footer      (box)+                                  >
<!ATTLIST  page_footer
             %style;
             height     CDATA                              #IMPLIED  >
<!--                    what goes at the top of the page when the
                        detail is continued from another page      -->
<!ELEMENT  partial_header    (box)+                                  >
<!ATTLIST  partial_header
             %style;
             height     CDATA                              #IMPLIED  >
<!--                    what goes at the bottom of the page when
                        the detail is continued on another page    -->
<!ELEMENT  partial_footer   (box)+                                  >
<!ATTLIST  partial_footer
             %style;
             height     CDATA                              #IMPLIED  >

<!ELEMENT  box               (#PCDATA | field | compute)*            >
<!ATTLIST  box
             %style;
             line       CDATA                              "0"
             column     CDATA                              #REQUIRED
             width      CDATA                              #IMPLIED
             height     CDATA                              #IMPLIED
             align      (right|left|center)                "left"
             vfill      (true|false)                       "false"
             raw        (true|false)                       "false"
             wrap       (true|false)                       "false"   >

<!ELEMENT  detail_entry      (box)+                                  >
<!ATTLIST  detail_entry
             %style;
             height     CDATA                              #IMPLIED  
             name       NMTOKEN                            #REQUIRED >

<!ELEMENT  field             EMPTY                                   >
<!ATTLIST  field
             name       NMTOKEN                            #REQUIRED
             default    CDATA                              #IMPLIED  >

<!ELEMENT  compute      EMPTY                                        >
<!ATTLIST  compute
             watch      CDATA                              #IMPLIED
             expr       CDATA                              #REQUIRED >

=== BackupTheBerlios/ruff-svn/trunk/examples/Reporte-new.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!--
# Copyright 2003,2004 Fundación Vía Libre
#
# This file is part of ruff.
#
# ruff is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# ruff is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PAPO; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-->


<!DOCTYPE report SYSTEM "../../ruff/ruff.dtd">
<report name="cierre_caja" height="60">
  <header height="3">
    <box column="0">Planilla de Caja Diaria</box>
    <box column="48" align="right" width="32"><field name="fecha" default="[ sin fecha ]"/></box>
  </header>
  <detail name="ingresos">
    <header height="2">
      <box column="0" width="32" align="center">Ingresos</box>
      <box column="33" width="11" align="center">Contado</box>
      <box column="45" width="11" align="center">Cheque</box>
      <box column="57" width="11" align="center">Otros</box>
      <box column="69" width="11" align="center">TOTAL</box>
    </header>
    <detail_entry name="item">
      <box column="1" width="32" align="left" wrap="true"><field name="concepto"/></box>
      <box column="33" width="11" align="right"><field name="cash"/></box>
      <box column="45" width="11" align="right"><field name="cheque"/></box>
      <box column="57" width="11" align="right"><field name="otros"/></box>
      <box column="69" width="11" align="right"><field name="total"/></box>
    </detail_entry>
  </detail>
  <detail name="egresos">
    <header height="3">
      <box line="1" column="0" width="32" align="center">Egresos</box>
      <box line="1" column="33" width="11" align="center">Contado</box>
      <box line="1" column="45" width="11" align="center">Cta. Cte.</box>
      <box line="1" column="57" width="11" align="center">Otros</box>
      <box line="1" column="69" width="11" align="center">TOTAL</box>
    </header>
    <detail_entry name="item">
      <box column="1" width="32" align="left" wrap="true"><field name="concepto"/></box>
      <box column="33" width="11" align="right"><field name="cash"/></box>
      <box column="45" width="11" align="right"><field name="cheque"/></box>
      <box column="57" width="11" align="right"><field name="otros"/></box>
      <box column="69" width="11" align="right"><field name="total"/></box>
    </detail_entry>
  </detail>
  <detail name="diferencia">
    <header height="3">
      <box line="1" column="0" width="32" align="center">DIFERENCIA</box>
      <box line="1" column="33" width="11" align="center">Contado</box>
      <box line="1" column="45" width="11" align="center">Cta. Cte.</box>
      <box line="1" column="57" width="11" align="center">Otros</box>
      <box line="1" column="69" width="11" align="center">TOTAL</box>
    </header>
    <detail_entry name="item">
      <box column="1" width="32" align="left" wrap="true"><field name="moneda"/></box>
      <box column="33" width="11" align="right"><field name="contado"/></box>
      <box column="45" width="11" align="right"><field name="ctacte"/></box>
      <box column="57" width="11" align="right"><field name="otros"/></box>
      <box column="69" width="11" align="right"><field name="total"/></box>
    </detail_entry>
  </detail>
  <footer height="1">
  </footer>
  <page_footer height="1">
    <box column="10" vfill="true" raw="true">-----</box>
  </page_footer>
</report>

=== BackupTheBerlios/ruff-svn/trunk/examples/Reporte.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!--
Copyright 2003 Fundacion Via Libre

This file is part of PAPO.

PAPO is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

PAPO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PAPO; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-->

<!DOCTYPE detail SYSTEM "ruff.dtd">
<detail name="cierre_caja">
  <page_header>
    <box column="0">Planilla de Caja Diaria</box>
    <box column="100" align="right" width="32"><field name="fecha"/></box>
    <box line="2" column="0" width="132" raw="true">อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออัอออออออออออัอออออออออออัอออออออออออัออออออออออออ</box>
  </page_header>
  <detail name="ingresos">
    <page_header>
      <box column="0" width="82" align="center">Ingresos</box>
      <box column="83" raw="true">ณ</box>
      <box column="84" width="11" align="center">cash</box>
      <box column="95" raw="true">ณ</box>
      <box column="96" width="11" align="center">cheque</box>
      <box column="107" raw="true">ณ</box>
      <box column="108" width="11" align="center">otros</box>
      <box column="119" raw="true">ณ</box>
      <box column="120" width="11" align="center">TOTAL</box>
      <box line="2" column="0" width="132" raw="true">ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤ</box>
    </page_header>
    <detail_entry name="item">
      <box column="1" width="82" align="left" wrap="true"><field name="concepto"/></box>
      <box column="83" vfill="true" raw="true">ณ</box>
      <box column="84" width="11" align="right"><field name="cash"/></box>
      <box column="95" vfill="true" raw="true">ณ</box>
      <box column="96" width="11" align="right"><field name="cheque"/></box>
      <box column="107" vfill="true" raw="true">ณ</box>
      <box column="108" width="11" align="right"><field name="otros"/></box>
      <box column="119" vfill="true" raw="true">ณ</box>
      <box column="120" width="11" align="right"><field name="total"/></box>
    </detail_entry>
    <footer>
      <box column="0" width="132" raw="true">ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤ</box>
      <box line="2" column="1" width="82" align="left" wrap="true">TOTAL</box>
      <box line="2" column="83" raw="true">ณ</box>
      <box line="2" column="84" width="11" align="right"><field name="cash"/></box>
      <box line="2" column="95" raw="true">ณ</box>
      <box line="2" column="96" width="11" align="right"><field name="cheque"/></box>
      <box line="2" column="107" raw="true">ณ</box>
      <box line="2" column="108" width="11" align="right"><field name="otros"/></box>
      <box line="2" column="119" raw="true">ณ</box>
      <box line="2" column="120" width="11" align="right"><field name="total"/></box>
    </footer>
  </detail>
  <detail_entry name="inter">
    <box column="0" raw="true">อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออุอออออออออออุอออออออออออุอออออออออออุออออออออออออ</box>
  </detail_entry>
  <detail name="egresos">
    <page_header>
      <box column="0" width="82" align="center">Egresos</box>
      <box column="83" raw="true">ณ</box>
      <box column="84" width="11" align="center">cash</box>
      <box column="95" raw="true">ณ</box>
      <box column="96" width="11" align="center">cheque</box>
      <box column="107" raw="true">ณ</box>
      <box column="108" width="11" align="center">otros</box>
      <box column="119" raw="true">ณ</box>
      <box column="120" width="11" align="center">TOTAL</box>
      <box line="2" column="0" width="132" raw="true">ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤ</box>
    </page_header>
    <detail_entry name="item">
      <box column="1" width="82" align="left"><field name="concepto"/></box>
      <box column="83" raw="true">ณ</box>
      <box column="84" width="11" align="right"><field name="cash"/></box>
      <box column="95" raw="true">ณ</box>
      <box column="96" width="11" align="right"><field name="cheque"/></box>
      <box column="107" raw="true">ณ</box>
      <box column="108" width="11" align="right"><field name="otros"/></box>
      <box column="119" raw="true">ณ</box>
      <box column="120" width="11" align="right"><field name="total"/></box>
    </detail_entry>
    <footer>
      <box column="0" width="132" raw="true">ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤ</box>
      <box line="2" column="1" width="82" align="left" wrap="true">TOTAL</box>
      <box line="2" column="83" raw="true">ณ</box>
      <box line="2" column="84" width="11" align="right"><field name="cash"/></box>
      <box line="2" column="95" raw="true">ณ</box>
      <box line="2" column="96" width="11" align="right"><field name="cheque"/></box>
      <box line="2" column="107" raw="true">ณ</box>
      <box line="2" column="108" width="11" align="right"><field name="otros"/></box>
      <box line="2" column="119" raw="true">ณ</box>
      <box line="2" column="120" width="11" align="right"><field name="total"/></box>
    </footer>
  </detail>
  <footer>
    <box column="0" raw="true">อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออุอออออออออออุอออออออออออุอออออออออออุออออออออออออ</box>
      <box line="2" column="1" width="82" align="left" wrap="true">SALDO</box>
      <box line="2" column="83" raw="true">ณ</box>
      <box line="2" column="84" width="11" align="right"><field name="cash"/></box>
      <box line="2" column="95" raw="true">ณ</box>
      <box line="2" column="96" width="11" align="right"><field name="cheque"/></box>
      <box line="2" column="107" raw="true">ณ</box>
      <box line="2" column="108" width="11" align="right"><field name="otros"/></box>
      <box line="2" column="119" raw="true">ณ</box>
      <box line="2" column="120" width="11" align="right"><field name="total"/></box>
    <box line="3" column="0" width="132" raw="true">อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออฯอออออออออออฯอออออออออออฯอออออออออออฯออออออออออออ</box>
  </footer>
</detail>
